config/routes.rb
Groupin::Application.routes.draw do
  resources :events
  get "home/index"
  devise_for :users
  post 'event_attendence', to: 'events#event_attendence', as: 'event_attedence'

    root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
   if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, EventAttendence
      can :event_attendence, Event
      #can :update, Event
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :address, :city_name, :contact_number, :country_name,
                  :end_time, :event_date, :name, :no_of_people,
                  :pincode, :start_time, :state_name, :no_of_people_present

   validates_presence_of :city_name
   extend FriendlyId
   friendly_id :name, use: :slugged
  
   has_many :event_attendences
 
 
   def should_generate_new_friendly_id?
     new_record? || slug.blank?
   end 
 
   #acts_as_gmappable :process_geocoding => true 
   acts_as_gmappable :check_process => false

   def gmaps4rails_address
     address
   end

   def gmaps4rails_infowindow
     "<h5>Name/Address: <br><a href='/events/#{slug}'></h4>" << "<h4>#{address}</h4>"
   end
 
   def gmaps4rails_sidebar
    name
   end
  
end

app/models/event_attendence.rb
class EventAttendence < ActiveRecord::Base
  attr_accessible :event_id, :user_id, :status
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :terms, :admin
  #validates_acceptance_of :terms
  validates_uniqueness_of :email, :first_name, :last_name,
                          :message => Proc.new { |error, attributes|
                          "#{attributes[:value]} has already been taken."},  :on => :create


  validates :terms, :acceptance => true
  # attr_accessible :title, :body


  #before_validation(on: :create) do
  #  self.admin = true
  #end

  def full_name 
    self.first_name + ' ' + self.last_name
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
    rescue_from CanCan::AccessDenied do |exception|
     redirect_to main_app.root_url, :alert => exception.message
    end

    def check_session
     if session[:user]
       if session[:expiry_time] < 1.minutes.ago
         reset_session
       flash[:warning] = 'You waass logout.' 
         redirect_to root_url
       else
         session[:expiry_time] = Time.now
       end
     else
       #... authenticate
       session[:expiry_time] = Time.now
       flash[:warning] = 'You wass logout.' 
       redirect_to root_url
     end
    end  


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  #before_filter :check_session
  before_filter :authenticate_user!, :except => [:index, :show]

  #skip_before_filter :authenticate_user!, :only => [:new, :destroy]
  load_and_authorize_resource 
  include ApplicationHelper

  # GET /events
  # GET /events.json
  def index
    @events = Event.order("name").page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @json = Event.find(params[:id]).to_gmaps4rails
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
  
  def event_attendence
   @event_id = Event.find(params[:event_id])
   @user_id = User.find(params[:user_id])
   @status =  params[:status]
   @attendence = EventAttendence.create(:event_id => @event_id.id, :user_id => @user_id.id, :status => @status )
    if @attendence.save!
       @event_attendence = @attendence.event.update_attributes(:no_of_people_present => (@attendence.event.no_of_people_present)+1)
     redirect_to events_path , :notice => "Thank you for coming"
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  
  def index
   #@latest_events = latest_events(Date.today-10, Date.today)
   #@json = Event.all.to_gmaps4rails
   @json = Event.all.to_gmaps4rails
    @polyjson = []
    points = []

    Event.all.each do |l|
      points << {:lng => l.longitude, :lat => l.latitude}
    end
    @polyjson = [points].to_json
 end

end

app/helpers/application_helper.rb
module ApplicationHelper

 def simple_class_for flash_type
   case flash_type
   when :success
   "alert-success"
   when :error
   "alert-error"
   when :alert
   "alert-block"
   when :notice
   "alert-info"
   else
   flash_type.to_s
   end
 end


 def difference_of_days_between(date)
   time_ago_in_words(date)
 end

  def latest_events(start_date, end_date)
    @le = Event.find_all_by_event_date(start_date..end_date)
  end   
end

app/helpers/events_helper.rb
module EventsHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
    
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address, :size=> "43x10" %>
  </div>
  <div class="field">
    <%= f.label :pincode %><br />
    <%= f.text_field :pincode %>
  </div>
  <div class="field">
    <%= f.label :city_name %><br />
    <%= f.text_field :city_name %>
  </div>
  <div class="field">
    <%= f.label :state_name %><br />
    <%= f.text_field :state_name %>
  </div>
  <div class="field">
    <%= f.label :country_name %><br />
    <%= f.text_field :country_name %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br />
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br> 
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :no_of_people %><br />
    <%= f.number_field :no_of_people %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.text_field :contact_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% @events.each do |event| %>
    <h2>*<%= link_to event.name, event %></h2> |
    <b>*<%= link_to event.name, event %></b> |
         <%= link_to 'Edit', edit_event_path(event) %> | <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        <h3>RSVP will be closed in <u><%= difference_of_days_between(event.event_date + 1) %></u></h3>
        <%= event.no_of_people %> Peoples <br><br>
        
          Total attendece :<br>
            <% event.event_attendences.each do |a| %>
             <%= a.user.full_name %>(<b style ="color:green"><%= a.status %></b>) |
            <% end %> <br><br>
   <% if signed_in? %>  
    <% if can? :create, EventAttendence %>
        <b><%= link_to "Yes, Coming", event_attedence_path(:user_id => current_user.id, :event_id => event, :status => "yes, coming"), :method => :post  %> | 
        <%= link_to "Not Coming", event_attedence_path(:user_id => current_user.id, :event_id => event, :status => "not coming"), :method => :post  %> | 
        <%= link_to "May be", event_attedence_path(:user_id => current_user.id, :event_id => event, :status => "may be"), :method => :post  %></b><br><br>
    <% end %>    
   <% else %>
    <b>* Register/Login to join this Event </b>
   <% end %>         
  <% if user_signed_in? %>
    <% if can? :create, EventAttendence %>
     <b><%= link_to "Yes, Coming", event_attedence_path(:user_id => current_user.id, :event_id => event, :status => "yes, coming"), :method => :post  %> | 
     <%= link_to "Not Coming", event_attedence_path(:user_id => current_user.id, :event_id => event, :status => "not coming"), :method => :post  %> | 
     <%= link_to "May be", event_attedence_path(:user_id => current_user.id, :event_id => event, :status => "may be"), :method => :post  %></b><br><br>
    <% end %>         
    <% else %>
    <b> <%= link_to 'Login', new_user_session_path %> or <%= link_to 'Register', new_user_registration_path %> to attend this event </b>
  <% end %>
    <hr>
<% end %>
<br>
<%= paginate @events, :outer_window => 3 %><br><br>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<div class="total_attendence"> 
 <h2> Attendies in this event </h2>
 <% @event.event_attendences.each do |a| %>
  <%= a.user.full_name %> |
 <% end %>
</div>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Address:</b>
  <%= @event.address %>
</p>

<p>
  <b>Pincode:</b>
  <%= @event.pincode %>
</p>

<p>
  <b>City name:</b>
  <%= @event.city_name %>
</p>

<p>
  <b>State name:</b>
  <%= @event.state_name %>
</p>

<p>
  <b>Country name:</b>
  <%= @event.country_name %>
</p>

<p>
  <b>Event date:</b>
  <%= time_tag @event.event_date %>
</p>

<p>
  <b>Start time:</b>
  <%= @event.start_time.strftime("%H:%M:%S %P") %>
</p>

<p>
  <b>End time:</b>
  <%= @event.end_time.strftime("%H:%M:%S %P") %>
</p>

<p>
  <b>No of people:</b>
  <%= @event.no_of_people %>
</p>

<p>
  <b>Contact number:</b>
  <%= @event.contact_number %>
</p>


	<%= gmaps(:markers => {:data => @json, :options => { :raw => '{ animation: google.maps.Animation.BOUNCE }' } },
	          :map_options => {  "auto_zoom" => false, "zoom" => 10, :raw => '{ disableDefaultUI: true, scrollwheel: false }' }) %> <br><br>
	          
	          

app/views/home/index.html.erb
<div id="maps">
   <%= gmaps(:markers => {:data => @json, :options => { :raw => '{ animation: google.maps.Animation.BOUNCE }' } },
             :map_options => { "auto_zoom" => false, "zoom" => 10, :raw => '{ disableDefaultUI: true, scrollwheel: false }' }) %> <br><br>
</div>

<% if Event.any? %>
  <div id="body-data">
      <div id="previous_event">
      <h4><%= link_to Event.last.name, Event.last %></h4>
      <%= Event.last.address %><br>
      no of seats: <%= Event.last.no_of_people_present %><br>
      Total Attendence :<%= Event.last.no_of_people %>
    </div>
    <div id ="current_event">
      <h4><%= link_to Event.first.name, Event.first %></h4>
      <%= Event.first.address %><br>
      no of seats: <%= Event.first.no_of_people_present %><br>
      Total Attendence :<%= Event.first.no_of_people %>
    </div>
    <h4><%= link_to "View All Events", events_path %></h4>

    <br><Br>
  </div>
	<br><Br>
</div>
<% end %>

<div id="footer-data" style="width:600px;">
      <logo style ="font-size:30px;"> Contact Us </logo>
      <br><br>
      <a href="https://www.facebook.com/groups/MumbaiOnRails/"> <%= image_tag ('facebook-64px.png') %></a>
      <a href="https://groups.google.com/forum/#!forum/mrug"> <%= image_tag ('google-64px.png') %></a>
      <a href="https://twitter.com/MumbaiOnRails"> <%= image_tag ('twitter-64px.png') %> </a>
</div>

app/views/layouts/_flash_messages.html.erb
<%= render partial: "shared/flash_messages", flash: flash %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groupin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <link href='http://fonts.googleapis.com/css?family=Sarina' rel='stylesheet' type='text/css'>

  <style>
    body {font-family: 'Ubuntu', sans-serif;font-size:12px;}
    logo{ text-shadow: 0.1em 0.1em 0.05em #333;
    font-family: 'Sarina', cursive; font-size:70px;color:orange}
  </style>

</head>

 <body style="padding:40px;">

 <logo> Mumbai on rails </logo><br>
  <div class="bs-docs-example" style ="float:right;font-size:12px;">
      <% if signed_in? %>
       <%= link_to current_user.full_name %>(<% if current_user.admin? %> <b style="color:blue">Admin</b> <% else %> Moderator <% end %>) | 
       <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %> |
       <%= link_to "Edit Account", edit_user_registration_path %> | 
       <b><%= link_to 'Add Event', new_event_path if current_user.admin? %></b> |
       <b><%= link_to 'Back to Home', root_url %></b> 
      <% else %>
       <%= link_to "login", new_user_session_path %> |
       <%= link_to "signup", new_user_registration_path %> |
       <b><%= link_to 'Back to Home', root_url %></b> 
      <% end %>
  </div>
  <br>

</div>

<hr>
<br><br><br>
<% flash.each do |type, message| %>
 <div class="alert <%= simple_class_for(type) %> fade in">
  <%= message %>
 </div>
<% end %>
<div id ="content" style="width:610px;">
 <%= yield %>
 <%= yield :scripts %>
</body>
<footer>
</footer>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groupin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <link href='http://fonts.googleapis.com/css?family=Sarina' rel='stylesheet' type='text/css'>
  <style>
    body {font-family: 'Ubuntu', sans-serif;font-size:15px;}
    logo{ text-shadow: 0.1em 0.1em 0.05em #333;
    font-family: 'Sarina', cursive; font-size:70px;color:orange}
  </style>
</head>

<body style="padding:40px;">
 <logo> Mumbai On rails </logo><br>
</div>

<hr>
<br><br><br>
<% flash.each do |type, message| %>
	<div class="alert <%= simple_class_for(type) %> fade in">
		<%= message %>
	</div>
<% end %>

<div id ="content" style="width:610px;">
	 <%= yield %>
	 <%= yield :scripts %>
</body>
</html>